UsefulWebApps/Controllers/ArtWorkController.cs
using Microsoft.AspNetCore.Mvc;
using UsefulWebApps.Models.ViewModels.ArtWork;

namespace UsefulWebApps.Controllers
{
    public class ArtWorkController : Controller
    {
        private IWebHostEnvironment Environment;
        public ArtWorkController(IWebHostEnvironment _environment)
        {
            Environment = _environment;
        }
        public IActionResult Index(int page)
        {
            IEnumerable<string> paths = Directory.EnumerateFiles(Path.Combine(this.Environment.WebRootPath, "images/artwork/"));
            List<string> files = new List<string>();
            List<string> filesToShow = new List<string>();
            if (page == 0)
            {
                page = 1;
            }
           
            int limit = 4;
            int offset = (limit * (page - 1));
            //count is total number of images
            int count = paths.Count();
            int totalPages = (int)Math.Ceiling(count / (double)limit);

            foreach (string path in paths)
            {
                files.Add(Path.GetFileName(path));
            }

            if (page < totalPages)
            {
                //works until last page because last page may have less than 10 elements
                filesToShow = files.GetRange(offset, limit);
            }
            //for last page skip the rest
            else if (page == totalPages) 
            {
                filesToShow = new List<string>(files.Skip(offset));
        
            }
            
            ArtWorkVM artWorkVM = new() 
            { 
                FilesToShow = filesToShow,
                CurrentPage = page,
                TotalPages = totalPages,
            };
            return View(artWorkVM);
        }
    }
}

UsefulWebApps/Controllers/MyHomePageController.cs
using Ganss.Xss;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using UsefulWebApps.Models.MyHomePage;
using UsefulWebApps.Models.ViewModels.MyHomePage;
using UsefulWebApps.Repository.IRepository;

namespace UsefulWebApps.Controllers
{
    [Authorize(Roles = "StandardUser, Admin")]
    [AutoValidateAntiforgeryToken]
    public class MyHomePageController : Controller
    {
        private HtmlSanitizer sanitizer = new HtmlSanitizer();
        private IWebHostEnvironment Environment;
        private readonly IUnitOfWork _unitOfWork;
        public MyHomePageController(IWebHostEnvironment _environment, IUnitOfWork unitOfWork)
        {
            Environment = _environment;
            _unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> Index()
        {
            ClaimsPrincipal currentUser = this.User;
            string userId = currentUser.FindFirstValue(ClaimTypes.NameIdentifier);

            //get users slideshow choice
            List<SlideShowImages> userSlideShowImages = await _unitOfWork.SlideShow.GetSlideShowImagesForUser(userId);
            //if user doesnt have a choice the space images will be displayed
            IEnumerable<string> paths = Directory.EnumerateFiles(Path.Combine(this.Environment.WebRootPath, "images/customhomepage/space/"));
           
            List<string> filesToShow = new List<string>();
            foreach (string path in paths)
            {
                filesToShow.Add(Path.GetFileName(path));
            }
            
            //get the users quick links
            List<QuickLinks> userQuickLinks = await _unitOfWork.QuickLinks.GetQuickLinksForUser(userId);

            //get a random quote
            Quotes randomQuote = await _unitOfWork.Quotes.GetRandomRow();
            
            MyHomePageVM myHomePageVM = new() 
            { 
                SlideShowImagesToDisplay = userSlideShowImages,
                DefaultSlideShowImagesToDisplay = filesToShow,
                QuickLinksToDisplay = userQuickLinks,
                RandomQuote = randomQuote
            };
            return View(myHomePageVM);
        }

        public async Task<IActionResult> SelectQuickLinks() 
        {
            ClaimsPrincipal currentUser = this.User;
            string userId = currentUser.FindFirstValue(ClaimTypes.NameIdentifier);

            (
                List<QuickLinks> userQuickLinks, 
                List<QuickLinks> allQuickLinks
            ) result = await _unitOfWork.QuickLinks.GetQuickLinksForEditDisplay(userId);

            List<QuickLinks> userQuickLinks = result.userQuickLinks;
            List<QuickLinks> allQuickLinks = result.allQuickLinks;


            foreach (QuickLinks allql in allQuickLinks) 
            {
                if (userQuickLinks.Any(userql => userql.QuickLinkId == allql.QuickLinkId))
                {
                    allql.IsSelected = true;
                }
            }
            SelectQuickLinksVM selectQuickLinksVM = new() 
            { 
                AllQuickLinks = allQuickLinks
            };

            return View(selectQuickLinksVM);
        }

        [HttpPost]
        public async Task<IActionResult> SelectQuickLinks(SelectQuickLinksVM selectQuickLinksVM)
        {
            ClaimsPrincipal currentUser = this.User;
            string userId = currentUser.FindFirstValue(ClaimTypes.NameIdentifier);
            string userName = currentUser.FindFirstValue(ClaimTypes.Name);

            if (ModelState.IsValid) 
            {
                bool success = await _unitOfWork.QuickLinks.UpdateQuickLinks(userId, userName, selectQuickLinksVM);
                if (success)
                {
                    TempData["success"] = "Quick links updated successfully";
                }
                else
                {
                    TempData["error"] = "Update quick link error. Please try again.";
                }
                return RedirectToAction("Index");
            }
            TempData["error"] = "Update quick link error. Please try again.";
            return RedirectToAction("Index");
        }
        
        public async Task<IActionResult> SelectSlideShow()
        {
            ClaimsPrincipal currentUser = this.User;
            string userId = currentUser.FindFirstValue(ClaimTypes.NameIdentifier);
            (SlideShowFolder userSlideShowFolder, List<SlideShowFolder> allSlideShowFolders) result = await _unitOfWork.SlideShow.GetSlideShowFoldersEditDisplay(userId);
            SlideShowFolder userSlideShowFolder = result.userSlideShowFolder;
            List<SlideShowFolder> allSlideShowFolders = result.allSlideShowFolders;
            //will be null if user has never picked a slideshow folder
            if (userSlideShowFolder != null)
            {
                foreach (SlideShowFolder slideShowFolder in allSlideShowFolders)
                {
                    if (slideShowFolder.FolderName == userSlideShowFolder.FolderName)
                    {
                        slideShowFolder.IsSelected = true;
                    }
                }
            }
            
            SelectSlideShowVM selectSlideShowVM = new() { SlideShowFolders = allSlideShowFolders };
            return View(selectSlideShowVM);
        }
        [HttpPost]
        public async Task<IActionResult> SelectSlideShow(SelectSlideShowVM selectSlideShowVM)
        {
            ClaimsPrincipal currentUser = this.User;
            string userId = currentUser.FindFirstValue(ClaimTypes.NameIdentifier);

            if (ModelState.IsValid)
            {
                bool success = await _unitOfWork.SlideShow.UpdateSlideShow(userId, selectSlideShowVM);
                if (success)
                {
                    TempData["success"] = "Slideshow updated successfully";
                }
                else
                {
                    TempData["error"] = "Update slideshow error. Please try again.";
                }
                return RedirectToAction("Index");
            }
            TempData["error"] = "Update slideshow error. Please try again.";
            return RedirectToAction("Index");
        }

        public IActionResult CreateQuote()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateQuote(Quotes obj)
        {
            obj.Quote = sanitizer.Sanitize(obj.Quote);
            if (ModelState.IsValid) 
            {
                bool success = await _unitOfWork.Quotes.Add(obj);
                if (success)
                {
                    TempData["success"] = "Quote added successfully";
                }
                else
                {
                    TempData["error"] = "Add quote error. Please try again.";
                }
                return RedirectToAction("Index");
            }
            TempData["error"] = "Add quote error. Please try again.";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> EditQuote(int? id) 
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Quotes quote = await _unitOfWork.Quotes.GetById(id);
            return View(quote);
        }

        [HttpPost]
        public async Task<IActionResult> EditQuote(Quotes obj)
        {
            obj.Quote = sanitizer.Sanitize(obj.Quote);
            if (ModelState.IsValid) 
            { 
                bool success = await _unitOfWork.Quotes.Update(obj);
                if (success)
                {
                    TempData["success"] = "Quote edited successfully.";
                    return RedirectToAction("Index");
                }
                TempData["error"] = "Edit quote error. Try again.";
                return RedirectToAction("index");
            }
            TempData["error"] = "Edit quote error. Try again.";
            return RedirectToAction("index");
        }
    }
}

UsefulWebApps/Controllers/WeatherController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text.Json;
using UsefulWebApps.Helpers.Weather;
using UsefulWebApps.Models.ViewModels.Weather;
using UsefulWebApps.Models.Weather;
using UsefulWebApps.Repository.IRepository;

namespace UsefulWebApps.Controllers
{
    [Authorize(Roles = "StandardUser, Admin")]
    [AutoValidateAntiforgeryToken]
    public class WeatherController : Controller
    {
        private static string apiKey = ManageAPIKey.GetAPIKey();
        private static readonly HttpClient client = new HttpClient();

        private readonly IUnitOfWork _unitOfWork;
        public WeatherController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> Index()
        {
            ClaimsPrincipal currentUser = this.User;
            string userId = currentUser.FindFirstValue(ClaimTypes.NameIdentifier);
            List<Locations> locations = (List<Locations>)await _unitOfWork.Locations.GetAllWhere("UserId", userId);
            LocationsVM locationsVM = new() { Locations = locations };
            return View(locationsVM);
        }

        public IActionResult AddLocations()
        {
            ClaimsPrincipal currentUser = this.User;
            string userId = currentUser.FindFirstValue(ClaimTypes.NameIdentifier);
            Locations location = new() 
            { 
                UserId = userId
            };
            return View(location);
        }

        [HttpPost]
        public async Task<IActionResult> AddLocations(Locations locationObj)
        {
            if (ModelState.IsValid)
            {
                //get location lat and lon
                string jsonLocation = string.Empty;
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                if (locationObj.Country.ToUpper() == "US" && locationObj.State.ToUpper() != "NA")
                {
                    try
                    {
                        jsonLocation = await client.GetStringAsync($"http://api.openweathermap.org/geo/1.0/direct?q={locationObj.City},{locationObj.State},{locationObj.Country}&limit=1&appid={apiKey}");
                    }
                    catch(Exception e)
                    {
                        TempData["error"] = $"Sorry the api returned an error. {e.Message}";
                        return View();
                    }
                }
                else if (locationObj.Country.ToUpper() != "US" && locationObj.State.ToUpper() == "NA")
                {
                    try
                    {
                        jsonLocation = await client.GetStringAsync($"http://api.openweathermap.org/geo/1.0/direct?q={locationObj.City},{locationObj.Country}&limit=1&appid={apiKey}");
                    }
                    catch (Exception e)
                    {
                        TempData["error"] = $"Sorry the api returned an error. {e.Message}";
                        return View();
                    }
                }
                else
                {
                    TempData["error"] = "Sorry that was an invalid input";
                    return View();
                }
                //always a list of lenght 1 -- limit 1 on api call above
                List<LocationJSON> locationList = JsonSerializer.Deserialize<List<LocationJSON>>(jsonLocation);
                //if nothing in list the api didnt find the location.
                if (locationList.Count == 0)
                {
                    TempData["error"] = "Sorry the api could not find that location";
                    return View();
                }
                Locations location = new()
                {
                    City = locationList[0].Name,
                    Latitude = locationList[0].Latitude,
                    Longitude = locationList[0].Longitude,
                    Country = locationList[0].Country,
                    State = locationList[0].State,
                    UserId = locationObj.UserId,
                    IsDefault = locationObj.IsDefault,
                };
                //add location to data base
                bool success = await _unitOfWork.Locations.Add(location);
                if (success) 
                {
                    TempData["success"] = "Location Added successfully.";
                    return RedirectToAction("Index");
                }
                TempData["error"] = "Add location error. Try again.";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Add location error. Try again.";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Weather(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Locations location = await _unitOfWork.Locations.GetById(id);
            //get weather for lat and lon
            string jsonCurrentWeather = string.Empty;
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            try
            {
                jsonCurrentWeather = await client.GetStringAsync($"https://api.openweathermap.org/data/2.5/weather?lat={location.Latitude}&lon={location.Longitude}&units=imperial&appid={apiKey}");
            }
            catch (Exception e) 
            {
                TempData["error"] = $"Sorry the api returned an error. {e.Message}";
                return RedirectToAction("Index");
            }

            CurrentWeatherJSON currentWeather = JsonSerializer.Deserialize<CurrentWeatherJSON>(jsonCurrentWeather);
            //get forecast for lat and lon
            string jsonForecast = string.Empty;
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            try
            {
                jsonForecast = await client.GetStringAsync($"https://api.openweathermap.org/data/2.5/forecast?lat={location.Latitude}&lon={location.Longitude}&units=imperial&appid={apiKey}");
            }
            catch (Exception e) 
            {
                TempData["error"] = $"Sorry the api returned an error. {e.Message}";
                return RedirectToAction("Index");
            }
            ForecastWeatherJSON forecastWeather = JsonSerializer.Deserialize<ForecastWeatherJSON>(jsonForecast);
            
            CurrentWeatherVM currentWeatherVM = new()
            {
                Location = location,
                CurrentWeatherJSON = currentWeather,
                ForecastWeatherJSON = forecastWeather
            };

            return View(currentWeatherVM);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteLocation(int? id)
        {
            if (!ModelState.IsValid) 
            {
                TempData["error"] = "Delete location error. Try again.";
                return RedirectToAction("Index");
            }
            bool success = await _unitOfWork.Locations.Delete(id);
            if (success)
            {
                TempData["success"] = "Location deleted successfully.";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["error"] = "Delete location error. Try again.";
                return RedirectToAction("Index");
            }
        }
    }
}

UsefulWebApps/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Useful Web Apps</title>
    <link rel="stylesheet" href="~/css/custom.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/toastrjs/toastr.min.js"></script>
    <link rel="stylesheet" href="~/lib/toastrjs/toastr.min.css" />
</head>
<body class="text-dark">
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Useful Web Apps</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole("Admin") || User.IsInRole("StandardUser"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="ListBuddy" asp-action="Index">List Buddy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="MyRecipes" asp-action="Index">My Recipes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="MyHomePage" asp-action="Index">Custom Home Page</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Weather" asp-action="Index">Weather</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="ArtWork" asp-action="Index">Artwork</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Manage">Manage Accounts</a>
                            </li>
                        }
                        <li class="nav-item">
                            <partial name="_LoginStatusPartial" />
                        </li>
                        <li class="nav-item">
                            @if (User == null || User.Identity == null || User.Identity.IsAuthenticated)
                            {
                                <span class="nav-link link-light">Welcome @User?.Identity?.Name</span>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="footer bg-dark text-light">
        <div class="container">
            <span>&copy; 2024 - Useful Web Apps</span>
        </div>
    </footer>
    <!--<script src="~/lib/jquery/dist/jquery.min.js"></script>-->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UsefulWebApps/Views/Shared/_LoginStatusPartial.cshtml
@if (User == null || User.Identity == null || User.Identity.IsAuthenticated)
{
    <form method="post" class="form-inline" asp-controller="Account" asp-action="Logout">
        <button type="submit" class="nav-link">Logout</button>
    </form>
}
else
{
    <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
}

UsefulWebApps/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}