UsefulWebApps/Models/MyRecipes/Recipe.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using UsefulWebApps.CustomValidation;

namespace UsefulWebApps.Models.MyRecipes
{
    [Table("recipes")]
    public class Recipe
    {
        [Key]
        [Column("RecipeId")]
        public int RecipeId { get; set; }

        [Column("RecipeTitle")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "Please enter at least 3 characters.")]
        [Required(ErrorMessage = "Recipe title is required.")]
        public string RecipeTitle { get; set; } = string.Empty;

        [Column("RecipeDescription")]
        //allow null empty RecipeDescription
        [ValidateNever]
        [StringLength(200, MinimumLength = 0)]
        public string RecipeDescription { get; set; } = string.Empty;

        [ForeignKey("CourseId")]
        [Column("CourseId")]
        public int CourseId { get; set; }

        [ForeignKey("CuisineId")]
        [Column("CuisineId")]
        public int CuisineId { get; set; }

        [ForeignKey("DifficultyId")]
        [Column("DifficultyId")]
        public int DifficultyId { get; set; }

        [Column("PrepTime")]
        [Required(ErrorMessage = "Enter a prep time")]
        [Range(0, ushort.MaxValue)]
        public ushort PrepTime { get; set; }

        [Column("CookTime")]
        [Required(ErrorMessage = "Enter a cook time")]
        [Range(0, ushort.MaxValue)]
        public ushort CookTime { get; set; }

        [Column("Rating")]
        [Required(ErrorMessage = "Enter a number between 1 and 10")]
        [Range(1, 10)]
        public byte Rating { get; set; }

        [Column("Servings")]
        [Required(ErrorMessage = "Enter a number between 1 and 20")]
        [Range(1, 20)]
        public byte Servings { get; set; }

        [Column("Nutrition")]
        //allow null empty Nutrition
        [ValidateNever]
        [StringLength(2000, MinimumLength = 0)]
        public string Nutrition { get; set; } = string.Empty;

        [Column("Ingredients")]
        [Required(ErrorMessage = "Recipe ingredients is required.")]
        [StringLength(3000, MinimumLength = 3, ErrorMessage = "Please enter at least 3 characters.")]
        public string Ingredients { get; set; } = string.Empty;

        [Column("Instructions")]
        [Required(ErrorMessage = "Recipe instructions is required.")]
        [StringLength(3000, MinimumLength = 3, ErrorMessage = "Please enter at least 3 characters.")]
        public string Instructions { get; set; } = string.Empty;

        [Column("Notes")]
        //allow null empty Notes
        [ValidateNever]
        [StringLength(2000, MinimumLength = 0)]
        public string Notes { get; set; } = string.Empty;

        [Column("UserId")]
        [Required(ErrorMessage = "User Id is required.")]
        public string UserId { get; set; } = string.Empty;

        [Column("UserName")]
        [Required(ErrorMessage = "User Name is required.")]
        public string UserName { get; set; } = string.Empty;

        [Column("ImagePath")]
        //allow null empty ImagePath
        [ValidateNever]
        [StringLength(500, MinimumLength = 0)]
        public string ImagePath { get; set; } = string.Empty;

        //fields for table JOINS
        //MANY TO MANY -- one recipe can have many categories -- one category can have many recipes
        [Required]
        [RequireRecipeCategoriesList]
        public List<RecipeCategories> Categories { get; set; } = new List<RecipeCategories>();

        //ONE TO MANY -- one recipe can have one course cuisine or difficulty --- one course cuisine or difficulty can have many recipes
        [Required]
        public RecipeCourses Course { get; set; }
        [Required]
        public RecipeCuisines Cuisine { get; set; }
        [Required]
        public RecipeDifficulties Difficulty { get; set; }

    }
}

UsefulWebApps/Models/MyRecipes/RecipeCategories.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UsefulWebApps.Models.MyRecipes
{
    [Table("recipe_categores")]
    public class RecipeCategories
    {
        [Key]
        [Column("CategoryId")]
        public int CategoryId { get; set; }

        [Column("Category")]
        [Required(ErrorMessage = "Recipe category is required.")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Please enter at least 3 characters.")]
        public string Category { get; set; }

        //fields for table JOINS
        //MANY TO MANY -- one recipe can have many categories -- one category can have many recipes
        public List<Recipe> Recipes { get; set; } = new List<Recipe>();
        public bool IsChecked { get; set; } = false;
    }
}

UsefulWebApps/Models/MyRecipes/RecipeComment.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace UsefulWebApps.Models.MyRecipes
{
    [Table("recipe_comments")]
    public class RecipeComment
    {
        [Key]
        [Column("CommentId")]
        public int CommentId { get; set; }

        [Column("Comment")]
        [Required(ErrorMessage = "Recipe comment is required.")]
        [StringLength(1000, MinimumLength = 10, ErrorMessage = "Please enter at least 10 characters.")]
        public string Comment { get; set; } = string.Empty;

        [Column("UserId")]
        [Required(ErrorMessage = "User Id is required.")]
        public string UserId { get; set; } = string.Empty;

        [Column("UserName")]
        [Required(ErrorMessage = "User Name is required.")]
        public string UserName { get; set; } = string.Empty;

        [ForeignKey("RecipeId")]
        [Column("RecipeId")]
        public int RecipeId { get; set; }
    }
}

UsefulWebApps/Models/MyRecipes/RecipeCourses.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UsefulWebApps.Models.MyRecipes
{
    [Table("recipe_courses")]
    public class RecipeCourses
    {
        [Key]
        [Column("CourseId")]
        public int CourseId { get; set; }

        [Column("Course")]
        [Required(ErrorMessage = "Recipe course is required.")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Please enter at least 3 characters.")]
        public string Course { get; set; }

        //fields for table JOINS
        //ONE TO MANY -- one recipe can have one course cuisine or difficulty --- one course cuisine or difficulty can have many recipes
        public List<Recipe> Recipes { get; set; } = new List<Recipe>();

        public bool IsChecked { get; set; } = false;
    }
}

UsefulWebApps/Models/MyRecipes/RecipeCuisines.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UsefulWebApps.Models.MyRecipes
{
    [Table("recipe_cuisines")]
    public class RecipeCuisines
    {
        [Key]
        [Column("CuisineId")]
        public int CuisineId { get; set; }

        [Column("Cuisine")]
        [Required(ErrorMessage = "Recipe cuisine is required.")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Please enter at least 3 characters.")]
        public string Cuisine { get; set; }

        //fields for table JOINS
        //ONE TO MANY -- one recipe can have one course cuisine or difficulty --- one course cuisine or difficulty can have many recipes
        public List<Recipe> Recipes { get; set; } = new List<Recipe>();

        public bool IsChecked { get; set; } = false;
    }
}

UsefulWebApps/Models/ViewModels/MyRecipes/SavedRecipesVM.cs
using UsefulWebApps.Models.MyRecipes;

namespace UsefulWebApps.Models.ViewModels.MyRecipes
{
    public class SavedRecipesVM
    {
        public List<RecipeUserSaved> RecipeUserSaved { get; set; }
    }
}

UsefulWebApps/Controllers/MyRecipesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using UsefulWebApps.Models.MyRecipes;
using UsefulWebApps.Models.ViewModels.MyRecipes;
using UsefulWebApps.Repository.IRepository;
using Ganss.Xss;

namespace UsefulWebApps.Controllers
{
    [Authorize(Roles = "StandardUser, Admin")]
    [AutoValidateAntiforgeryToken]
    public class MyRecipesController : Controller
    {
        private IWebHostEnvironment Environment;
        private HtmlSanitizer sanitizer = new HtmlSanitizer();
        private readonly IUnitOfWork _unitOfWork;
        public MyRecipesController(IUnitOfWork unitOfWork, IWebHostEnvironment _environment)
        {
            Environment = _environment;
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index(int page, string searchString)
        {
            
            if (page == 0)
            {
                page = 1;
            }
            //limit is the number of recipes per page
            int limit = 10;
            int offset = (limit * (page - 1));

            (int count, List<Recipe> recipes) result = await _unitOfWork.Recipe.Pagination(limit, offset, searchString);

            //count is the total number of recipes in database when search sting in empty or the total
            //number of retured recipes that match the search string
            int count = result.count;
            List<Recipe> recipes = result.recipes;

            int totalPages = (int)Math.Ceiling(count / (double)limit);

            RecipeIndexVM recipeIndexVM = new()
            {
                Recipes = recipes,
                CurrentPage = page,
                TotalPages = totalPages,
                TotalRecipes = count,
                SearchString = searchString,
            };
            
            return View(recipeIndexVM);
        }

        public async Task<IActionResult> Recipe(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            ClaimsPrincipal currentUser = this.User;
            string userId = currentUser.FindFirstValue(ClaimTypes.NameIdentifier);
            string userName = currentUser.FindFirstValue(ClaimTypes.Name);

            RecipePageVM RecipePageVM = await _unitOfWork.Recipe.GetRecipeAndCommentsById(id);
            RecipePageVM.RecipeComment.UserId = userId;
            RecipePageVM.RecipeComment.UserName = userName;
            RecipePageVM.RecipeUserSaved.UserId = userId;
            RecipePageVM.RecipeUserSaved.UserName = userName;
            return View(RecipePageVM);
        }

        public async Task<IActionResult> SavedRecipes()
        {
            ClaimsPrincipal currentUser = this.User;
            string userId = currentUser.FindFirstValue(ClaimTypes.NameIdentifier);
            List<RecipeUserSaved> recipeUserSaved = await _unitOfWork.Recipe.GetUserSavedRecipes(userId);
            SavedRecipesVM savedRecipesVM = new SavedRecipesVM 
            { 
                RecipeUserSaved = recipeUserSaved,
            };
            if(recipeUserSaved.Count == 0)
            {
                TempData["success"] = "You don't have any saved recipes.";
            }
            return View(savedRecipesVM);
        }

        [HttpPost]
        [Route("/MyRecipes/PostComment", Name = "postComment")]
        public async Task<IActionResult> PostComment(RecipeComment recipeComment)
        {
            if (ModelState.IsValid)
            {
               
                int? id = recipeComment.RecipeId;
                bool success = await _unitOfWork.Recipe.AddRecipeComment(recipeComment);
                if (success)
                {
                    TempData["success"] = "Posted comment successfully";
                    return RedirectToAction("Recipe", new { id });
                }
                else
                {
                    TempData["error"] = "Post comment error. Please try again.";
                    return RedirectToAction("Index");
                }
            }
            TempData["error"] = "Post comment error. Please try again.";
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("/MyRecipes/UserSavedRecipe", Name = "userSavedRecipe")]
        public async Task<IActionResult> UserSavedRecipe(RecipeUserSaved recipeUserSaved)
        {
            if (ModelState.IsValid)
            {
                int? id = recipeUserSaved.RecipeId;
                bool success = await _unitOfWork.Recipe.AddUserSavedRecipe(recipeUserSaved);
                if (success)
                {
                    TempData["success"] = "Recipe saved to your list successfully";
                    return RedirectToAction("Recipe", new { id });
                }
                else
                {
                    TempData["error"] = "You can only save 10 recipes to your list";
                    return RedirectToAction("Recipe", new { id });
                }
            }
            TempData["error"] = "Save recipe to list error. Please try again.";
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("/MyRecipes/DeleteUserSavedRecipe", Name = "deleteUserSavedRecipe")]
        public async Task<IActionResult> DeleteUserSavedRecipe(int? id)
        {
            
            if (id == null || id == 0)
            {
                TempData["error"] = "Delete saved recipe error. Please try again";
                return RedirectToAction("SavedRecipes");
            }
            bool success = await _unitOfWork.Recipe.DeleteUserSavedRecipe(id);
            if (success)
            {
                TempData["success"] = "Saved recipe deleted successfully";
            }
            else
            {
                TempData["error"] = "Delete saved recipe error. Please try again";
            }
            return RedirectToAction("SavedRecipes");
        }

        public async Task<IActionResult> EditRecipe(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
          
            (
                List<Recipe> recipe, 
                List<RecipeCategories> recipeCategories,
                List<RecipeCourses> recipeCourses, 
                List<RecipeCuisines> recipeCuisines, 
                List<RecipeDifficulties> recipeDifficulties
            ) result = await _unitOfWork.Recipe.GetRecipeAndCategoriesForEditDisplay(id);

            //https://www.learndapper.com/relationships -- map the JOIN to C# objects
            //this is a list of 1 single recipe listed x times one for each category -- best to see this by running the above sql in workbench. 
            List<Recipe> recipe = result.recipe;

            //since we sql SELECT on 1 id GroupBy returns 1 group with x num recipe rows
            //foreach group get the First recipe and add the categories to it
            //this returns a list with 1 recipe in it that now has List<RecipeCategories> filled
            List<Recipe> filteredRecipe = recipe.GroupBy(r => r.RecipeId).Select(g =>
            {
                Recipe singleRecipe = g.First();
                //select each recipe in the group and return the list of categories
                singleRecipe.Categories = g.Select(r => r.Categories.Single()).ToList();
                return singleRecipe;
            }).ToList();

            List<RecipeCategories> recipeCategories = result.recipeCategories;
            List<RecipeCourses> recipeCourses = result.recipeCourses;
            List<RecipeCuisines> recipeCuisines = result.recipeCuisines;
            List<RecipeDifficulties> recipeDifficulties = result.recipeDifficulties;

            //add IsChecked to recipeCategories
            for (int i = 0; i < recipeCategories.Count; i++)
            {
                for (int j = 0; j < filteredRecipe[0].Categories.Count; j++)
                {
                    if (recipeCategories[i].CategoryId == filteredRecipe[0].Categories[j].CategoryId)
                    {
                        recipeCategories[i].IsChecked = true;
                    }
                }
            }
            //add IsChecked to recipeCourses
            for (int i = 0; i < recipeCourses.Count; i++)
            {
                if (recipeCourses[i].CourseId == filteredRecipe[0].Course.CourseId)
                {
                    recipeCourses[i].IsChecked = true;
                }
            }
            //add IsChecked to recipeCuisines
            for (int i = 0; i < recipeCuisines.Count; i++)
            {
                if (recipeCuisines[i].CuisineId == filteredRecipe[0].Cuisine.CuisineId)
                {
                    recipeCuisines[i].IsChecked = true;
                }
            }
            for (int i = 0; i < recipeDifficulties.Count; i++)
            {
                if (recipeDifficulties[i].DifficultyId == filteredRecipe[0].Difficulty.DifficultyId)
                {
                    recipeDifficulties[i].IsChecked = true;
                }
            }

            RecipeVM recipeVM = new()
            {
                Recipe = filteredRecipe[0],
                RecipeCategories = recipeCategories,
                RecipeCourses = recipeCourses,
                RecipeCuisines = recipeCuisines,
                RecipeDifficulties = recipeDifficulties
            };

            ClaimsPrincipal currentUser = this.User;
            string userId = currentUser.FindFirstValue(ClaimTypes.NameIdentifier);
            string role = currentUser.FindFirstValue(ClaimTypes.Role);

            if (recipeVM.Recipe.UserId != userId && role != "Admin")
            {
                TempData["error"] = $"Only the author {recipeVM.Recipe.UserName} can edit this recipe";
                return RedirectToAction("Recipe", new { id } );
            }

            return View(recipeVM);
        }

        [HttpPost]

UsefulWebApps/Views/MyRecipes/CreateRecipe.cshtml
@{
    ViewData["Title"] = "Create Recipe";
}

@model UsefulWebApps.Models.ViewModels.MyRecipes.RecipeVM

<div class="max-width-700 mx-auto container pb-3">
    <h1 class="mt-3 mb-3 text-center">Create Recipe</h1>
    <form asp-controller="MyRecipes" asp-action="CreateRecipe" method="post" id="createRecipeForm" enctype="multipart/form-data">
        <h3 class="mt-3 text-center">Title</h3>
        <div class="form-floating mb-3">
            <input asp-for="Recipe.RecipeTitle" type="text" class="form-control" placeholder="Recipe Title" minlength="3" required />
            <label asp-for="Recipe.RecipeTitle">Recipe Title</label>
            <span asp-validation-for="Recipe.RecipeTitle" class="text-danger"></span>
        </div>
        <h3 class="mt-3 text-center">Description</h3>
        <div class="form-floating">
            <textarea asp-for="Recipe.RecipeDescription" class="form-control ignore" placeholder="Recipe Description"></textarea>
            <label asp-for="Recipe.RecipeDescription">Recipe Description</label>
        </div>
        <h3 class="mt-3 text-center">Recipe Image</h3>
        <div>
            <label asp-for="ImageFile" class="form-label">Choose Image</label>
            <input asp-for="ImageFile" type="file" class="form-control ignore" placeholder="Choose Image" accept="image/*" />
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-6 col-lg-6">
                <h3 class="mt-3 text-center">Course</h3>
                <p class="fs-7">Check one.</p>
                <!--hidden input just for jquery validate-->
                <input type="hidden" name="courseError" id="courseError" />
                <ul class="list-group mt-3 choice-list">
                    @for (int i = 0; i < Model.RecipeCourses.Count; i++)
                    {
                        <li class="list-group-item list-group-item-action active">
                            <input class="form-check-input me-1 course-radio-btn" type="radio" asp-for="Recipe.CourseId" value="@Model.RecipeCourses[i].CourseId" checked="@(Model.RecipeCourses[i].IsChecked == true ? "checked" : null )" />
                            @Model.RecipeCourses[i].Course
                            <input type="hidden" asp-for="@Model.RecipeCourses[i].Course" />
                            <input type="hidden" asp-for="@Model.RecipeCourses[i].CourseId" />
                        </li>
                    }
                </ul>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-6">
                <h3 class="mt-3 text-center">Cuisine</h3>
                <p class="fs-7">Check one.</p>
                <!--hidden input just for jquery validate-->
                <input type="hidden" name="cuisineError" id="cuisineError" />
                <ul class="list-group mt-3 choice-list">
                    @for (int i = 0; i < Model.RecipeCuisines.Count; i++)
                    {
                        <li class="list-group-item list-group-item-action active">
                            <input class="form-check-input me-1 cuisine-radio-btn" type="radio" asp-for="Recipe.CuisineId" value="@Model.RecipeCuisines[i].CuisineId" checked="@(Model.RecipeCuisines[i].IsChecked == true ? "checked" : null)" />
                            @Model.RecipeCuisines[i].Cuisine
                            <input type="hidden" asp-for="@Model.RecipeCuisines[i].Cuisine" />
                            <input type="hidden" asp-for="@Model.RecipeCuisines[i].CuisineId" />
                        </li>
                    }
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-6 col-lg-6">
                <h3 class="mt-3 text-center">Difficulty</h3>
                <p class="fs-7">Check one.</p>
                <!--hidden input just for jquery validate-->
                <input type="hidden" name="difficultyError" id="difficultyError" />
                <ul class="list-group mt-3">
                    @for (int i = 0; i < Model.RecipeDifficulties.Count; i++)
                    {
                        <li class="list-group-item list-group-item-action active">
                            <input class="form-check-input me-1 difficulty-radio-btn" type="radio" asp-for="Recipe.DifficultyId" value="@Model.RecipeDifficulties[i].DifficultyId" checked="@(Model.RecipeDifficulties[i].IsChecked == true ? "checked" : null)" />
                            @Model.RecipeDifficulties[i].Difficulty
                            <input type="hidden" asp-for="@Model.RecipeDifficulties[i].Difficulty" />
                            <input type="hidden" asp-for="@Model.RecipeDifficulties[i].DifficultyId" />
                        </li>
                    }
                </ul>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-6">
                <!-- https://stackoverflow.com/questions/40555543/how-do-i-implement-a-checkbox-list-in-asp-net-core -->
                <h3 class="mt-3 text-center">Tags</h3>
                <p class="fs-7">Check at least one tag.</p>
                <!--hidden input just for jquery validate-->
                <input type="hidden" name="tags" id="tags" />
                <span asp-validation-for="Recipe.Categories" class="text-danger"></span>
                <ul class="list-group mt-3 choice-list">
                    @for (int i = 0; i < Model.RecipeCategories.Count; i++)
                    {
                        <li class="list-group-item list-group-item-action active">
                            <input class="form-check-input me-1 tags-ck-box" type="checkbox" asp-for="@Model.RecipeCategories[i].IsChecked" />
                            <label class="form-check-label stretched-link" asp-for="@Model.RecipeCategories[i].IsChecked">@Model.RecipeCategories[i].Category</label>
                            <input type="hidden" asp-for="@Model.RecipeCategories[i].CategoryId" />
                            <input type="hidden" asp-for="@Model.RecipeCategories[i].Category" />
                        </li>
                    }
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-6 col-lg-6">
                <h3 class="mt-3 text-center">Prep Time</h3>
                <div class="form-floating mb-3">
                    <input asp-for="Recipe.PrepTime" type="number" step="1" max="65535" min="0" class="form-control" required />
                    <label asp-for="Recipe.PrepTime">Prep Time - Minutes</label>
                    <span asp-validation-for="Recipe.PrepTime" class="text-danger"></span>
                </div>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-6">
                <h3 class="mt-3 text-center">Cook Time</h3>
                <div class="form-floating mb-3">
                    <input asp-for="Recipe.CookTime" type="number" step="1" max="65535" min="0" class="form-control" required />
                    <label asp-for="Recipe.CookTime">Cook Time - Minutes</label>
                    <span asp-validation-for="Recipe.CookTime" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-6 col-lg-6">
                <h3 class="mt-3 text-center">Rating</h3>
                <div class="form-floating mb-3">
                    <input asp-for="Recipe.Rating" type="number" step="1" max="10" min="1" value="1" class="form-control" required />
                    <label asp-for="Recipe.Rating">Rating 1-10</label>
                    <span asp-validation-for="Recipe.Rating" class="text-danger"></span>
                </div>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-6">
                <h3 class="mt-3 text-center">Servings</h3>
                <div class="form-floating mb-3">
                    <input asp-for="Recipe.Servings" type="number" step="1" max="20" min="1" value="1" class="form-control" required />
                    <label asp-for="Recipe.Servings">Servings 1-20</label>
                    <span asp-validation-for="Recipe.Servings" class="text-danger"></span>
                </div>
            </div>
        </div>
        <p>
            The below inputs allow basic HTML so the recipe page can display numbered or bulleted lists.
            Click <a asp-action="Directions" asp-controller="Home" target="_blank">here</a> for more detail.
            <strong>Note:</strong> although you can edit and create recipes on your mobile phone its about a million times easier to use you pc.
        </p>
        <h3 class="mt-3 text-center">Ingredients</h3>
        <div class="form-floating">
            <textarea asp-for="Recipe.Ingredients" class="form-control textarea-input" minlength="3" required placeholder="Recipe Ingredients"></textarea>
            <label asp-for="Recipe.Ingredients">Recipe Ingredients</label>
            <span asp-validation-for="Recipe.Ingredients" class="text-danger"></span>
        </div>
        <h3 class="mt-3 text-center">Instructions</h3>
        <div class="form-floating">
            <textarea asp-for="Recipe.Instructions" class="form-control textarea-input" minlength="3" required placeholder="Recipe Instructions"></textarea>
            <label asp-for="Recipe.Instructions">Recipe Instructions</label>
            <span asp-validation-for="Recipe.Instructions" class="text-danger"></span>
        </div>
        <h3 class="mt-3 text-center">Notes</h3>
        <div class="form-floating">
            <textarea asp-for="Recipe.Notes" class="form-control textarea-input ignore" placeholder="Recipe Notes"></textarea>
            <label asp-for="Recipe.Notes">Recipe Notes</label>
        </div>
        <h3 class="mt-3 text-center">Nutrition</h3>
        <div class="form-floating mb-3">
            <textarea asp-for="Recipe.Nutrition" class="form-control textarea-input ignore" placeholder="Recipe Nutrition"></textarea>
            <label asp-for="Recipe.Nutrition">Recipe Nutrition</label>
        </div>
        <h3 class="mt-3 text-center">Author</h3>
        <div class="form-floating">
            <input type="hidden" asp-for="Recipe.UserId" />
            <input type="text" asp-for="Recipe.UserName" class="form-control" readonly placeholder="Author" />
            <label asp-for="Recipe.UserName">Author</label>
        </div>
        <div class="max-width-200 mx-auto">
            <div>
                <button class="btn btn-primary mb-3 mt-3 w-100" type="submit">Create Recipe</button>
            </div>
            <div>
                <a asp-controller="MyRecipes" asp-action="Index" class="btn btn-outline-dark w-100">Back To Recipe List</a>
            </div>
        </div>
    </form>
</div>

<!--Partial View scripts-->
@section Scripts {
    @{
            <partial name="_ValidationScriptsPartial" />
    }
    <script type="text/javascript">
        $("#createRecipeForm").validate({
            invalidHandler: function (event, validator) {
                var errors = validator.numberOfInvalids();
                if (errors) {
                    toastError();
                }
            },
            ignore: ".ignore",
            rules: {
                tags: {
                    required: function (element) {
                        var boxes = $('.tags-ck-box');
                        if (boxes.filter(':checked').length == 0) {
                            return true;
                        }
                        return false;
                    },
                    minlength: 1
                },
                courseError: {
                    required: function (element) {
                        var boxes = $('.course-radio-btn');
                        if (boxes.filter(':checked').length == 0) {
                            return true;
                        }
                        return false;
                    },
                    minlength: 1
                },
                cuisineError: {
                    required: function (element) {
                        var boxes = $('.cuisine-radio-btn');
                        if (boxes.filter(':checked').length == 0) {
                            return true;
                        }
                        return false;
                    },
                    minlength: 1
                },
                difficultyError: {
                    required: function (element) {
                        var boxes = $('.difficulty-radio-btn');
                        if (boxes.filter(':checked').length == 0) {
                            return true;
                        }
                        return false;
                    },
                    minlength: 1
                }
            },
            messages: {
                tags: "Please check at least one recipe tag.",
                courseError: "Please pick a recipe course.",
                cuisineError: "Please pick a recipe cuisine.",
                difficultyError: "Please pick a recipe difficulty."
            }
        });
        function toastError() {
            toastr.error("Please check the form for errors.");
        }
    </script>
}