UsefulWebApps/Models/ListBuddy/GroceryCategories.cs
using System.ComponentModel.DataAnnotations;

namespace UsefulWebApps.Models.ListBuddy
{
    public class GroceryCategories
    {
        public int Id { get; set; }

        [StringLength(50, MinimumLength = 3, ErrorMessage = "Please enter at least 3 characters.")]
        [Required(ErrorMessage = "Grocery category is required.")]
        public string Category { get; set; }
    }
}

UsefulWebApps/Models/ListBuddy/GroceryList.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UsefulWebApps.Models.ListBuddy
{
    [Table("grocery_list")]
    public class GroceryList
    {
        [Key]
        [Column("Id")]
        public int Id { get; set; }

        [Column("GroceryItem")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "Please enter at least 3 characters.")]
        [Required(ErrorMessage = "Grocery item is required.")]
        public string GroceryItem { get; set; } = string.Empty;

        [Column("Category")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Please enter at least 3 characters.")]
        [Required(ErrorMessage = "Grocery category is required.")]
        public string Category { get; set; } = string.Empty;

        [Column("Complete")]
        [Required]
        public bool Complete { get; set; }

        [Column("UserId")]
        [Required]
        public string UserId { get; set; } = string.Empty;

        [Column("SortOrder")]
        [Required]
        public int SortOrder { get; set; } = 1;
    }
}

UsefulWebApps/Models/ListBuddy/Notes.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UsefulWebApps.Models.ListBuddy
{
    [Table("notes")]
    public class Notes
    {
        [Key]
        [Column("Id")]
        public int Id { get; set; }

        [Column("Note")]
        [StringLength(5000, MinimumLength = 10, ErrorMessage = "Please Enter At Least 10 Characters.")]
        [Required(ErrorMessage = "Note Is Required.")]
        public string Note { get; set; } = string.Empty;

        [Column("UserId")]
        [Required]
        public string UserId { get; set; } = string.Empty;

        [Column("NoteTitle")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "Please Enter At Least 3 Characters.")]
        [Required(ErrorMessage = "Note Title Is Required.")]
        public string NoteTitle {  get; set; } = string.Empty;
    }
}

UsefulWebApps/Models/ListBuddy/ToDoList.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UsefulWebApps.Models.ListBuddy
{
    [Table("to_do_list")]
    public class ToDoList
    {
        [Key]
        [Column("Id")]
        public int Id { get; set; }

        [Column("ToDoItem")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "Please Enter At Least 3 Characters.")]
        [Required(ErrorMessage = "To Do Item Is Required.")]
        public string ToDoItem { get; set; } = string.Empty;

        [Column("Complete")]
        [Required]
        public bool Complete { get; set; }

        [Column("UserId")]
        [Required]
        public string UserId { get; set; } = string.Empty;

        [Column("ListTitle")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "Please Enter At Least 3 Characters.")]
        [Required(ErrorMessage = "List Title Is Required.")]
        public string ListTitle { get; set; } = string.Empty;
    }
}

UsefulWebApps/Models/ListBuddy/UserGroceryCategories.cs
namespace UsefulWebApps.Models.ListBuddy
{
    public class UserGroceryCategories
    {
        public string Category {  get; set; }   
        public int SortOrder { get; set; }
    }
}

UsefulWebApps/Models/ViewModels/ListBuddy/GroceryListEditVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using UsefulWebApps.Models.ListBuddy;

namespace UsefulWebApps.Models.ViewModels.ListBuddy
{
    public class GroceryListEditVM
    {
        public string Category { get; set; }
        public GroceryList GroceryList { get; set; }
        public IEnumerable<SelectListItem> GroceryCategoriesList { get; set; }
    }
}

UsefulWebApps/Models/ViewModels/ListBuddy/GroceryListVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using UsefulWebApps.Models.ListBuddy;

namespace UsefulWebApps.Models.ViewModels.ListBuddy
{
    public class GroceryListVM
    {
        public string Category { get; set; }
        public GroceryList GroceryList { get; set; }
        public IEnumerable<SelectListItem> GroceryCategoriesList { get; set; }
        public List<List<GroceryList>> FilteredGroceryListItems { get; set; }
        public List<UserGroceryCategories> UserSortedGroceryCategories { get; set; }
    }
}

UsefulWebApps/Models/ViewModels/ListBuddy/MyToDoListsVM.cs
namespace UsefulWebApps.Models.ViewModels.ListBuddy
{
    public class MyToDoListsVM
    {
        public List<string> MyToDoLists { get; set; }
    }
}

UsefulWebApps/Models/ViewModels/ListBuddy/NotesVM.cs
using UsefulWebApps.Models.ListBuddy;

namespace UsefulWebApps.Models.ViewModels.ListBuddy
{
    public class NotesVM
    {
        public List<Notes> Notes { get; set; }
    }
}

UsefulWebApps/Models/ViewModels/ListBuddy/ShareGroceryListVM.cs
using UsefulWebApps.IdentityModels;

namespace UsefulWebApps.Models.ViewModels.ListBuddy
{
    public class ShareGroceryListVM
    {
        public User Friend {  get; set; }
        public string UserId { get; set; }
    }
}

UsefulWebApps/Models/ViewModels/ListBuddy/ToDoListVM.cs
using UsefulWebApps.Models.ListBuddy;

namespace UsefulWebApps.Models.ViewModels.ListBuddy
{
    public class ToDoListVM
    {
        public ToDoList ToDoList { get; set; }
        public List<ToDoList> ToDoListItems { get; set; }
    }
}

UsefulWebApps/Controllers/ListBuddyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;
using UsefulWebApps.Models.ListBuddy;
using UsefulWebApps.Models.ViewModels.ListBuddy;
using UsefulWebApps.Repository.IRepository;
using Ganss.Xss;
using Microsoft.AspNetCore.Identity;


namespace UsefulWebApps.Controllers
{
    [Authorize(Roles = "StandardUser, Admin")]
    [AutoValidateAntiforgeryToken]
    public class ListBuddyController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;

        private HtmlSanitizer sanitizer = new HtmlSanitizer();
        private readonly IUnitOfWork _unitOfWork;

        public ListBuddyController(UserManager<IdentityUser> userManager, IUnitOfWork unitOfWork)
        {
            _userManager = userManager;

            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        #region Notes
        public async Task<IActionResult> MyNotes()
        {
            ClaimsPrincipal currentUser = this.User;
            string userId = currentUser.FindFirstValue(ClaimTypes.NameIdentifier);
            List<Notes> notes = (List<Notes>)await _unitOfWork.Notes.GetAllWhere("UserId", userId);
            NotesVM notesVM = new()
            {
                Notes = notes
            };
            return View(notesVM);
        }

        public async Task<IActionResult> Note(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Notes note = await _unitOfWork.Notes.GetById(id);
            return View(note);
        }

        public IActionResult CreateNote() 
        {
            ClaimsPrincipal currentUser = this.User;
            string userId = currentUser.FindFirstValue(ClaimTypes.NameIdentifier);
            Notes note = new()
            {
                UserId = userId
            };
            return View(note); 
        }

        [HttpPost]
        public async Task<IActionResult> CreateNote(Notes obj)
        {
            obj.Note = sanitizer.Sanitize(obj.Note);
            if (ModelState.IsValid)
            {
                bool success = await _unitOfWork.Notes.Add(obj);
                if (success)
                {
                    TempData["success"] = "Note created successfully.";
                    return RedirectToAction("MyNotes");
                }
                TempData["error"] = "Create note error. Try again.";
                return RedirectToAction("MyNotes");
            }
            TempData["error"] = "Create note error. Try again.";
            return RedirectToAction("MyNotes");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteNote(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            bool success = await _unitOfWork.Notes.Delete(id);
            if (success)
            {
                TempData["success"] = "Note deleted successfully.";
                return RedirectToAction("MyNotes");
            }
            TempData["error"] = "Delete note error. Try again.";
            return RedirectToAction("MyNotes");
        }

        public async Task<IActionResult> EditNote(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Notes note = await _unitOfWork.Notes.GetById(id);
            return View(note);
        }

        [HttpPost]
        public async Task<IActionResult> EditNote(Notes obj)
        {
            obj.Note = sanitizer.Sanitize(obj.Note);
            if (ModelState.IsValid)
            {
                bool success = await _unitOfWork.Notes.Update(obj);
                if (success)
                {
                    TempData["success"] = "Note edited successfully.";
                    return RedirectToAction("Note", new { id = obj.Id });
                }
                TempData["error"] = "Edit note error. Try again.";
                return RedirectToAction("MyNotes");
            }
            TempData["error"] = "Edit note error. Try again.";
            return RedirectToAction("MyNotes");
        }
        #endregion

        #region To Do List

        public async Task<IActionResult> MyToDoLists() 
        {
            ClaimsPrincipal currentUser = this.User;
            string userId = currentUser.FindFirstValue(ClaimTypes.NameIdentifier);
            List<string> myToDoLists = await _unitOfWork.ToDoList.GetMyToDoLists(userId);
            MyToDoListsVM myToDoListsVM = new()
            {
                MyToDoLists = myToDoLists,
            };
            return View(myToDoListsVM); 
        }

        public async Task<IActionResult> ToDoList(string list)
        {
            ClaimsPrincipal currentUser = this.User;
            string userId = currentUser.FindFirstValue(ClaimTypes.NameIdentifier);
            List<ToDoList> listItems = await _unitOfWork.ToDoList.GetAllItemsInList(userId, list);
            ToDoListVM toDoListVM = new()
            {
                ToDoListItems = listItems,
                ToDoList = new ToDoList
                {
                    UserId = userId,
                    ListTitle = list,
                }
            };
            return View(toDoListVM);
        }
        
        [HttpPost]
        public async Task<IActionResult> ToDoListToggleComplete(int? id, string listTitle)
        {
            if (id == null || id == 0 || listTitle == "" || listTitle == null)
            {
                return NotFound();
            }
            ClaimsPrincipal currentUser = this.User;
            string userId = currentUser.FindFirstValue(ClaimTypes.NameIdentifier);
            List<ToDoList> listItems = await _unitOfWork.ToDoList.ToDoListToggleComplete(id, userId, listTitle);
            ToDoListVM toDoListVM = new()
            {
                ToDoListItems = listItems,
                ToDoList = new ToDoList
                {
                    UserId = userId,
                    ListTitle = listTitle
                }
            };
            return PartialView("_ToDoListPartial", toDoListVM);
        }

        public IActionResult CreateToDoList()
        {
            ClaimsPrincipal currentUser = this.User;
            string userId = currentUser.FindFirstValue(ClaimTypes.NameIdentifier);
            ToDoList toDoList = new ToDoList
            {
                UserId = userId
            };

            return View(toDoList);
        }
        //create a new ToDoList
        [HttpPost]
        public async Task<IActionResult> CreateToDoList(ToDoList toDoList)
        {

            if (ModelState.IsValid) 
            {
                bool success = await _unitOfWork.ToDoList.Add(toDoList);
                if (success)
                {
                    TempData["success"] = "To do list created successfully.";
                    return RedirectToAction("ToDoList", new { list = toDoList.ListTitle });
                }
                else
                {
                    TempData["error"] = "Create to do list error. Try again.";
                    return RedirectToAction("MyToDoLists");
                }
            }
            TempData["error"] = "Create to do list error. Try again.";
            return RedirectToAction("MyToDoLists");
        }

        //add new item to already existing ToDoList
        [HttpPost]
        public async Task<IActionResult> ToDoListAddItem(ToDoList toDoList)
        {
            if (ModelState.IsValid)
            {
                List<ToDoList> listItems = await _unitOfWork.ToDoList.ToDoListAdd(toDoList);
                ToDoListVM toDoListVM = new()
                {
                    ToDoListItems = listItems,
                    ToDoList = new ToDoList
                    {
                        UserId = toDoList.UserId,
                        ListTitle= toDoList.ListTitle
                    }
                };
                return PartialView("_ToDoListPartial", toDoListVM);
            }
            return StatusCode(400);
        }

        [HttpPost]
        public async Task<JsonResult> ToDoListDeleteItem(int? id)
        {
            if (id == null || id == 0)
            {
                return Json("error id was 0 or null");
            }
            await _unitOfWork.ToDoList.Delete(id);
            string jsonString = """
            { 
                "deleteId": "ID"
            }
            """;
            jsonString = jsonString.Replace("ID", $"{id}");
            return Json(jsonString);
        }

        [HttpPost]
        [Route("/ListBuddy/ToDoListDeleteAll", Name = "deleteAllToDoList")]
        public async Task<IActionResult> ToDoListDeleteAll(ToDoList toDoList)
        {
            toDoList.ToDoItem = "dummy item";
            ModelState.Clear();
            TryValidateModel(toDoList);
            if (ModelState.IsValid) 
            {
                bool success = await _unitOfWork.ToDoList.DeleteAllItemsInList(toDoList.UserId, toDoList.ListTitle);
                if (success)
                {
                    TempData["success"] = "To do list deleted successfully.";
                }
                else
                {
                    TempData["error"] = "Delete to do list error. Try again.";
                }
                return RedirectToAction("MyToDoLists");
            }
            TempData["error"] = "Delete to do list error. Try again.";
            return RedirectToAction("MyToDoLists");
        }

        public async Task<IActionResult> ToDoListEdit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            } 
            ToDoList toDoList = await _unitOfWork.ToDoList.GetById(id);
            return View(toDoList);
        }

        [HttpPost]

UsefulWebApps/Views/ListBuddy/CreateNote.cshtml
@{
    ViewData["Title"] = "Create Note";
}
@model UsefulWebApps.Models.ListBuddy.Notes

<div class="max-width-550 mx-auto container pb-3">
    <h1 class="display-3 mt-3 text-center">Create Note</h1>
    <form method="post">
        <input type="hidden" asp-for="UserId" />
        <h3 class="mt-3 text-center">Title</h3>
        <div class="form-floating mb-3">
            <input asp-for="NoteTitle" type="text" class="form-control" placeholder="Note Title" minlength="3" maxlength="100" required />
            <label asp-for="NoteTitle">Note Title</label>
            <span asp-validation-for="NoteTitle" class="text-danger"></span>
        </div>
        <p>
            The below note input allow basic HTML.
            Click <a asp-action="Directions" asp-controller="Home" target="_blank">here</a> for more detail.
        </p>

        <h3 class="mt-3 text-center">Note</h3>
        <div class="form-floating">
            <textarea asp-for="Note" class="form-control textarea-input" minlength="10" maxlength="5000" required placeholder="Note"></textarea>
            <label asp-for="Note">Note</label>
            <span asp-validation-for="Note" class="text-danger"></span>
        </div>

        <div class="max-width-200 mx-auto">
            <div>
                <button class="btn btn-primary mb-3 mt-3 w-100" type="submit">Create Note</button>
            </div>
            <div>
                <a asp-controller="ListBuddy" asp-action="MyNotes" class="btn btn-outline-dark w-100">Back To My Notes</a>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

UsefulWebApps/Views/ListBuddy/CreateToDoList.cshtml
@{
    ViewData["Title"] = "Create To Do List";
}

@model UsefulWebApps.Models.ListBuddy.ToDoList

<div class="text-center max-width-550 mx-auto container pb-3">
    <h1 class="display-3 mt-3">New To Do List</h1>
    <form method="post" class="max-width-550">
        <div class="form-floating mb-3">
            <!--Complete default value is False-->
            <input asp-for="Complete" hidden />
            <input asp-for="UserId" hidden />
            <input asp-for="ListTitle" type="text" class="form-control" placeholder="List Title" minlength="3" maxlength="100" />
            <label asp-for="ListTitle">List Title</label>
            <span asp-validation-for="ListTitle" class="text-danger"></span>
        </div>
        <div class="form-floating mb-3">
            <input asp-for="ToDoItem" type="text" class="form-control" placeholder="New Item" minlength="3" maxlength="100" />
            <label asp-for="ToDoItem">New Item</label>
            <span asp-validation-for="ToDoItem" class="text-danger"></span>
        </div>
        <div class="max-width-200 mx-auto">
            <div>
                <button class="btn btn-primary mb-3 mt-3 w-100" type="submit">Create New List</button>
            </div>
            <div>
                <a asp-controller="ListBuddy" asp-action="MyToDoLists" class="btn btn-outline-dark w-100">Back To My Lists</a>
            </div>
        </div>
      
    </form>
    

</div>
<!--Partial View scripts-->
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

UsefulWebApps/Views/ListBuddy/EditNote.cshtml
@{
    ViewData["Title"] = "Edit Note";
}
@model UsefulWebApps.Models.ListBuddy.Notes

<div class="max-width-550 mx-auto container pb-3">
    <h1 class="display-3 mt-3 text-center">Edit Note</h1>
    <form method="post">
        <input type="hidden" asp-for="UserId" />
        <input type="hidden" asp-for="Id" />
        <h3 class="mt-3 text-center">Title</h3>
        <div class="form-floating mb-3">
            <input asp-for="NoteTitle" type="text" class="form-control" placeholder="Note Title" minlength="3" maxlength="100" required />
            <label asp-for="NoteTitle">Note Title</label>
            <span asp-validation-for="NoteTitle" class="text-danger"></span>
        </div>
        <p>
            The below note input allow basic HTML.
            Click <a asp-action="Directions" asp-controller="Home" target="_blank">here</a> for more detail.
        </p>

        <h3 class="mt-3 text-center">Note</h3>
        <div class="form-floating">
            <textarea asp-for="Note" class="form-control textarea-input" minlength="10" maxlength="5000" required placeholder="Note"></textarea>
            <label asp-for="Note">Note</label>
            <span asp-validation-for="Note" class="text-danger"></span>
        </div>

        <div class="max-width-200 mx-auto">
            <div>
                <button class="btn btn-primary mb-3 mt-3 w-100" type="submit">Edit Note</button>
            </div>
            <div>
                <a asp-controller="ListBuddy" asp-action="Note" asp-route-id="@Model.Id" class="btn btn-outline-dark w-100">Back To Note</a>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

UsefulWebApps/Views/ListBuddy/GroceryList.cshtml
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Antiforgery
@using UsefulWebApps.Models.ListBuddy
@{
    ViewData["Title"] = "Grocery List";
    var requestToken = Antiforgery.GetAndStoreTokens(Context).RequestToken;
}

@model UsefulWebApps.Models.ViewModels.ListBuddy.GroceryListVM

<div class="text-center max-width-550 mx-auto container pb-3">
    <input id="RequestVerificationToken" type="hidden" value="@requestToken" />
    <h1 class="display-3 mt-3">Grocery List</h1>
    <div id="grocery-list-container">
        <partial name="_GroceryListPartial" />
    </div>
    <form method="post" class="max-width-550" id="add-grocery-list-item">
        <div class="input-group mb-3 mt-3">
            <!--Complete default value is False-->
            <input asp-for="GroceryList.Complete" hidden />
            <input asp-for="GroceryList.UserId" hidden />
            <input asp-for="GroceryList.GroceryItem" type="text" class="form-control" placeholder="New Item" minlength="3" maxlength="100" />
            <button class="btn btn-outline-dark" type="submit">Add Item</button>
        </div>
        <div class="mb-3">
            <select class="form-select required" asp-for="Category" asp-items="Model.GroceryCategoriesList">
                <option selected value="">Please Select a Category</option>
            </select>
        </div>
        <div class="mb-2 mt-2" id="new-grocery-item-error"></div>
    </form>

    <div class="row">
        <div class="col-sm-12 col-md-6 col-lg-6 max-width-250 mx-auto">
            <form method="post" asp-route="deleteAllGroceryList" id="delete-all-grocery-list">
                <div>
                    <button type="submit" class="btn btn-danger mb-3 w-100">Delete All</button>
                </div>
            </form>
            <div>
                <a asp-controller="ListBuddy" asp-action="Index" class="btn btn-outline-dark mb-3 w-100">List Buddy Home</a>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-6 max-width-250 mx-auto">
            <div>
                <button type="button" onclick="saveUserList(`@Model.GroceryList.UserId`)" class="btn btn-primary mb-3 w-100">Save List</button>
            </div>
            <form method="post" asp-controller="ListBuddy" asp-action="UseSavedGroceryList" asp-route-userId="@Model.GroceryList.UserId" id="use-saved-grocery-list">
                <div>
                    <button class="btn btn-outline-dark mb-3 w-100">Use Saved List</button>
                </div>
            </form>
        </div>
    </div>
    <div class="max-width-250 mx-auto">
        <a asp-controller="ListBuddy" asp-action="ShareGroceryList" asp-route-userId="@Model.GroceryList.UserId" class="btn btn-primary mb-3 w-100">Share List</a>
    </div>
    <p>
        You can save a grocery list as a template to your account.<br />
        Note: Using a saved list will delete your current list items and saving a new list template will delete the old one.
    </p>
</div>
<!--Partial View scripts-->
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    <script type="text/javascript" src="/js/GroceryList.js"></script>
}

UsefulWebApps/Views/ListBuddy/GroceryListEdit.cshtml
@{
    ViewData["Title"] = "Edit Grocery List";
}

@model UsefulWebApps.Models.ViewModels.ListBuddy.GroceryListEditVM

<div class="text-center max-width-550 mx-auto container pb-3">
    <h1 class="display-3 mt-3">Edit</h1>
    <form asp-controller="ListBuddy" asp-action="GroceryListEdit" method="post">
        <div class="input-group mb-3 mt-3">
            <input asp-for="GroceryList.Id" hidden />
            <input asp-for="GroceryList.Complete" hidden />
            <input asp-for="GroceryList.UserId" hidden />
            <input asp-for="GroceryList.SortOrder" hidden />
            <input asp-for="GroceryList.GroceryItem" type="text" class="form-control" placeholder="New Item" />
            <button class="btn btn-outline-dark" type="submit">Edit Item</button>
        </div>
        <div>
            <select class="form-select" asp-for="Category" asp-items="Model.GroceryCategoriesList"></select>
        </div>
        <div class="mb-3">
            <span asp-validation-for="GroceryList.GroceryItem" class="text-danger"></span>
        </div>
        <div>
            <a asp-controller="ListBuddy" asp-action="GroceryList" class="btn btn-outline-dark">Back to List</a>
        </div>
    </form>
</div>

<!--Partial View scripts-->
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

UsefulWebApps/Views/ListBuddy/Index.cshtml
@{
    ViewData["Title"] = "List Buddy";
}

<div class="text-center container pb-3">
    <h1 class="display-3 mt-3">List Buddy</h1>
    <p>Choose a list template to use</p>
    <div class="list-group max-width-200 mx-auto">
        <a asp-controller="ListBuddy" asp-action="MyToDoLists" class="list-group-item list-group-item-action">My To Do Lists</a>
        <a asp-controller="ListBuddy" asp-action="GroceryList" class="list-group-item list-group-item-action">Grocery List</a> 
        <a asp-controller="ListBuddy" asp-action="MyNotes" class="list-group-item list-group-item-action">My Notes</a> 
    </div>
</div>

UsefulWebApps/Views/ListBuddy/MyNotes.cshtml
@{
    ViewData["Title"] = "My Notes";
}

@model UsefulWebApps.Models.ViewModels.ListBuddy.NotesVM

<div class="text-center container pb-3">
    <h1 class="display-3 mt-3">My Notes</h1>
    <div class="list-group max-width-250 mx-auto">
        @foreach (var note in Model.Notes)
        {
            <a asp-controller="ListBuddy" asp-action="Note" asp-route-id="@note.Id" class="list-group-item list-group-item-action">@note.NoteTitle</a>
        }
    </div>
    <div class="max-width-250 mx-auto mt-3">
        <div class="mb-3">
            <a asp-controller="ListBuddy" asp-action="CreateNote" class="btn w-100">Add New Note</a>
        </div>
        <div>
            <a asp-controller="ListBuddy" asp-action="Index" class="btn btn-outline-dark w-100">List Buddy Home</a>
        </div>
    </div>
</div>

UsefulWebApps/Views/ListBuddy/MyToDoLists.cshtml
@{
    ViewData["Title"] = "My To Do Lists";
}

@model UsefulWebApps.Models.ViewModels.ListBuddy.MyToDoListsVM

<div class="text-center container pb-3">
    <h1 class="display-3 mt-3">My To Do Lists</h1>
    <div class="list-group max-width-250 mx-auto">
        @foreach(string list in Model.MyToDoLists)
        {
            <a asp-controller="ListBuddy" asp-action="ToDoList" asp-route-list="@list" class="list-group-item list-group-item-action">@list</a>
        }
    </div>
    <div class="max-width-250 mx-auto mt-3">
        <div class="mb-3">
            <a asp-controller="ListBuddy" asp-action="CreateToDoList" class="btn w-100">Add New To Do List</a>
        </div>
        <div>
            <a asp-controller="ListBuddy" asp-action="Index" class="btn btn-outline-dark w-100">List Buddy Home</a>
        </div>
    </div>
</div>

UsefulWebApps/Views/ListBuddy/ToDoListEdit.cshtml
@{
    ViewData["Title"] = "Edit To Do List";
}

@model UsefulWebApps.Models.ListBuddy.ToDoList

<div class="text-center max-width-550 mx-auto container pb-3">
    <h1 class="display-3 mt-3">Edit</h1>
    <form method="post">
        <div class="input-group mb-3 mt-3">
            <input asp-for="Id" hidden />
            <input asp-for="Complete" hidden />
            <input asp-for="ListTitle" hidden />
            <input asp-for="ToDoItem" type="text" class="form-control" placeholder="New Item" />
            <input asp-for="UserId" hidden />
            <button class="btn btn-outline-dark" type="submit">Edit Item</button>
        </div>
        <div class="mb-3">
            <span asp-validation-for="ToDoItem" class="text-danger"></span>
        </div>
        <div>
            <a asp-controller="ListBuddy" asp-action="ToDoList" asp-route-list="@Model.ListTitle" class="btn btn-outline-dark">Back to List</a>
        </div>
    </form>
</div>

<!--Partial View scripts-->
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}